### ISSUE TITLE
Creation of a GatewayNetwork with ipamConfig failed

### ISSUE THREAD

**Issue by bfranchet-nx** [scaleway/crossplane-provider-scaleway#85]
Hi,

We are currently evaluating the scaleway crossplane provider.
I'm facing what's seems to me a bug while creating a GatewayNetwork with ipamConfig. The status of GatewayNetwork kubernetes resource indicate a config conflict problem between ipam_config and static_address :

```
spec:
  deletionPolicy: Delete
  forProvider:
    enableDhcp: true
    enableMasquerade: true
    gatewayId: fr-par-1/91d0df73-b03b-4f09-badb-d7c9886dd86c
    gatewayIdRef:
      name: vpc-pgw-az1-controler
    ipamConfig:
    - pushDefaultRoute: true
    privateNetworkId: fr-par/b8344394-d066-440e-8f86-c0f157a55cec
    privateNetworkIdRef:
      name: vpc-pn-public
    staticAddress: 172.16.12.2/22
    zone: fr-par-1
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: scw-config
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2024-07-29T14:54:41Z"
    message: |-
      observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "static_address": conflicts with ipam_config
      Conflicting configuration arguments: "ipam_config": conflicts with static_address
    reason: ReconcileError
    status: "False"
    type: Synced
```

The GatewayNetwork kubernetes manifest used is :
``` 
apiVersion: vpc.scaleway.upbound.io/v1alpha1
kind: GatewayNetwork
metadata:
  name: vpc-gtw-net-az1
spec:
  providerConfigRef:
    name: scw-config
  forProvider:
    gatewayIdRef:
      name: vpc-pgw-az1-controler
    privateNetworkIdRef:
      name: vpc-pn-public
    enableMasquerade: true
    ipamConfig:
      - pushDefaultRoute: true
    zone: fr-par-1
```

My guess is, once created inside the scaleway infra, the gateway-network has an ip which is report back in the associated kubernetes resource in the field staticAddress and then conflict with ipamConfig for the kubernetes resource controler.

By the way, it seems that the GatewayNetwork resource in kubernetes can't be deleted till the config conflict is solved.
