### ISSUE TITLE
IAM policy creation: rules[0] is wrongly formatted

### ISSUE THREAD

**Issue by MicheleSica** [scaleway/crossplane-provider-scaleway#88]
Hello

following the documentation https://marketplace.upbound.io/providers/scaleway/provider-scaleway/v0.3.0/resources/iam.scaleway.upbound.io/Policy/v1alpha1#doc:spec-forProvider-rule
We used the below rule
```
spec:
  forProvider:
    name: iam-policy
    rule:
      - permissionSetNames:
          - ObjectStorageObjectsWrite  
```     

But we got the error
```
    Message:               create failed: apply failed: scaleway-sdk-go: invalid argument(s): rules[0] is wrongly formatted, embedded message failed validation:
```

Do you have any suggestions?
Thanks in advance
